source ~/.dotfiles/bash/colors.sh
source ~/.dotfiles/bash/config.sh
source ~/.dotfiles/bash/aliases.sh
source ~/.dotfiles/bash/functions.sh
source ~/.dotfiles/bash/remove-merged-branches.sh
source ~/.dotfiles/bash/git-completion.sh
source ~/.dotfiles/bash/bash-completion.sh
source ~/.dotfiles/bash/private.sh
